### PR TITLE
Migrated project from CRA(create-react-app) to Vite

### PR DESCRIPTION
**Pull request by GIT-Gizmo**
I've successfully migrated your project from CRA to Vite. Check it out and have fun with the rest of your project

### CODE REVIEW

**Comment by albeniskerqeli10** [comment]
It's working fine now. Thanks for the help on this issue 🙏

**Review by albeniskerqeli10 — APPROVED** [review]
👍

**Comment by albeniskerqeli10** [comment]
It's working fine now. Thanks for the help on this issue 🙏

**Comment by GIT-Gizmo** [comment]
You're welcome 👍

**Pull request merged**
